version: '3'

services:
  microservice-data:
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5000;https://+:5001
      ConnectionStrings:LocalConnection: "Server=sql.bsite.net\\MSSQL2016;Database=rainbow_db_microservice;User=rainbow_db_microservice;Password=nQ@i3KRiYu5Eyu6"
    ports:
      - "5000:80"
      - "5001:443"
    restart: on-failure